name: Code Analysis

on:
  push:
    branches:
      - develop
      - feature/*
      - feat/*
      - hotfix/*
  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: api

jobs:
  larastan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan with Larastan
        run: ./vendor/bin/phpstan analyse --memory-limit=-1

  codesniffer:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP CodeSniffer
        run: ./vendor/bin/phpcs
